name: okello_bill_tool
description: Building Bill Tool with Okello

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: "3.3.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.4
  firebase_storage: ^10.3.6
  firebase_core: ^1.21.0
  flutter_facebook_auth: ^4.3.4
  flutter_bloc: ^8.0.1
  google_sign_in: ^5.4.0
  provider: ^6.0.3
  twitter_login: ^4.2.3
  hive: ^2.2.3
  path_provider: ^2.0.11
  equatable: ^2.0.3
  uuid: ^3.0.6
  flutter_hooks: ^0.18.5+1
  image_picker: ^0.8.5+3
  freezed_annotation: ^2.1.0
  loader_overlay: ^2.0.10
  connectivity_plus: ^2.3.6+1
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.4.5
  logger: ^1.1.0
  googleapis: ^9.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1


# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Homizio
      fonts:
        - asset: assets/fonts/Homizio-Bold.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
